// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tweakster
{
    internal sealed partial class Vsix
    {
        public const string Id = "0c8bd9fa-77d5-4563-ab57-9e01608c3d04";
        public const string Name = "Tweakster";
        public const string Description = @"A collection of minor fixes and tweaks for Visual Studio to reduce the paper cuts and make you a happier developer";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
