// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tweakster
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTweaksterPackageString = "590dcf32-ae09-49b9-b0e5-55d7ebf100d0";
        public static Guid guidTweaksterPackage = new Guid(guidTweaksterPackageString);

        public const string guidCommandsString = "85ce63b9-a773-45e0-9a60-9a96bc2ab40b";
        public static Guid guidCommands = new Guid(guidCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ReOpenDocument = 0x0100;
        public const int Restart = 0x0200;
    }
}