// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tweakster
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTweaksterPackageString = "590dcf32-ae09-49b9-b0e5-55d7ebf100d0";
        public static Guid guidTweaksterPackage = new Guid(guidTweaksterPackageString);

        public const string guidSolutionHasProjectsString = "db87ae42-32ad-434e-b53c-08cfddcc0935";
        public static Guid guidSolutionHasProjects = new Guid(guidSolutionHasProjectsString);

        public const string guidCommandsString = "85ce63b9-a773-45e0-9a60-9a96bc2ab40b";
        public static Guid guidCommands = new Guid(guidCommandsString);

        public const string guidVSDebugGroupString = "c9dd4a58-47fb-11d2-83e7-00c04f9902c1";
        public static Guid guidVSDebugGroup = new Guid(guidVSDebugGroupString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ReOpenDocument = 0x0100;
        public const int Restart = 0x0200;
        public const int OuputVerbosity = 0x0300;
        public const int OuputVerbosityList = 0x0301;
        public const int OutputVerbosityGroup = 0x0302;
        public const int ResetZoom = 0x0400;
        public const int JustMyCode = 0x0500;
        public const int JustMyCodeGroup = 0x0501;
        public const int FindInSolutionExplorer = 0x0600;
        public const int FindInSolutionExplorerGroup = 0x0601;
        public const int SearchInFolder = 0x0700;
        public const int LanguageSetting = 0x0800;
        public const int LanguageSettingGroup = 0x0801;
        public const int IDM_DEBUG_TOOLBAR = 0x0421;
    }
}