// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tweakster
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTweaksterPackageString = "590dcf32-ae09-49b9-b0e5-55d7ebf100d0";
        public static Guid guidTweaksterPackage = new Guid(guidTweaksterPackageString);

        public const string guidCommandsString = "85ce63b9-a773-45e0-9a60-9a96bc2ab40b";
        public static Guid guidCommands = new Guid(guidCommandsString);

        public const string guidVSDebugGroupString = "c9dd4a58-47fb-11d2-83e7-00c04f9902c1";
        public static Guid guidVSDebugGroup = new Guid(guidVSDebugGroupString);

        public const string guidNewFolderString = "5efc7975-14bc-11cf-9b2b-00aa00573819";
        public static Guid guidNewFolder = new Guid(guidNewFolderString);

        public const string guidFeedbackCmdSetString = "769a4361-ad47-4ff4-86d8-d13bfdb7ed65";
        public static Guid guidFeedbackCmdSet = new Guid(guidFeedbackCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ReOpenDocument = 0x0100;
        public const int RestartMenu = 0x0200;
        public const int RestartGroup = 0x0201;
        public const int RestartNormal = 0x0202;
        public const int RestartElevated = 0x0203;
        public const int OuputVerbosity = 0x0300;
        public const int OuputVerbosityList = 0x0301;
        public const int OutputVerbosityGroup = 0x0302;
        public const int ResetZoom = 0x0400;
        public const int JustMyCode = 0x0500;
        public const int JustMyCodeGroup = 0x0501;
        public const int FindInSolutionExplorer = 0x0600;
        public const int FindInSolutionExplorerGroup = 0x0601;
        public const int ExploreSuggestions = 0x0700;
        public const int LanguageSetting = 0x0800;
        public const int LanguageSettingGroup = 0x0801;
        public const int DuplicateWindow = 0x0900;
        public const int ClearRecentFiles = 0x1000;
        public const int ClearRecentFilesGroup = 0x1001;
        public const int ClearRecentProjects = 0x1010;
        public const int ClearRecentProjectsGroup = 0x1011;
        public const int SelectWholeLine = 0x1100;
        public const int IDM_DEBUG_TOOLBAR = 0x0421;
        public const int PROJECT_NEW_FOLDER = 0x00F5;
        public const int grpidFeedback = 0x1020;
    }
}